# Generated by Django 3.1.7 on 2021-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Skill title')),
                ('indicator', models.IntegerField(help_text='from 0 to 100', max_length=5, verbose_name='Skill indicator')),
                ('icon', models.ImageField(upload_to='skill_icon')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
